sudo: required
services:
    -  docker

before_install:
    -  docker build -t anurag/react-test -f ./client/Dockerfile.dev ./client

script:
    -  docker run -e CI=true anurag/react-test npm test

after_success:
    -  docker build -t anuragensemble/multi-client ./client
    -  docker build -t anuragensemble/multi-nginx ./nginx
    -  docker build -t anuragensemble/multi-server ./server
    -  docker build -t anuragensemble/multi-worker ./worker
    # Log in to the docker CLI
    -  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to docker hub
    -  docker push anuragensemble/multi-client
    -  docker push anuragensemble/multi-nginx
    -  docker push anuragensemble/multi-server
    -  docker push anuragensemble/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-477168569750
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id:
        secure: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
